#############################################################################
# Generated by PAGE version 6.0.1
#  in conjunction with Tcl version 8.6
#  Jan 09, 2021 10:04:27 PM IST  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { \
    image20 "." \
    image21 "." \
    image22 "." \
    image23 "." \
    image24 "." \
    image25 "." \
    image26 "." \
    image27 "." \
    image28 "." \
    image29 "." \
}
vTcl:create_project_images $image_list   ;# In image.tcl


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top42 {base} {
    global vTcl
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background #fff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 687x526+328+66
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1604 882
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    label $top.lab47 \
        -activebackground #f9f9f9 -activeforeground black -background #fff \
        -disabledforeground #a3a3a3 \
        -font {-family {Avenir Next Cyr Medium} -size 23 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Ladki Aankh Maare} 
    vTcl:DefineAlias "$top.lab47" "songName" vTcl:WidgetProc "Toplevel1" 1
    ttk::progressbar $top.tPr48 \
        -length 100 -value 60 
    vTcl:DefineAlias "$top.tPr48" "songProgress" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $top.tLa51 \
        -background #fff -foreground #3399ff \
        -font {-family {Avenir Next Cyr} -size 9 -weight bold -slant roman -underline 0 -overstrike 0} \
        -relief flat -text 2:10 
    vTcl:DefineAlias "$top.tLa51" "songTotalDuration" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $top.tLa53 \
        -background #ffffff -foreground $vTcl(actual_gui_fg) \
        -font {-family {Avenir Next Cyr} -size 9 -weight bold -slant roman -underline 0 -overstrike 0} \
        -relief flat -text 1:15 
    vTcl:DefineAlias "$top.tLa53" "songTimePassed" vTcl:WidgetProc "Toplevel1" 1
    button $top.but61 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #fff -borderwidth 0 -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -image image24 -pady 0 -text Button 
    vTcl:DefineAlias "$top.but61" "pauseButton" vTcl:WidgetProc "Toplevel1" 1
    button $top.but62 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #fff -borderwidth 0 -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -image image25 -pady 0 -text Button 
    vTcl:DefineAlias "$top.but62" "playButton" vTcl:WidgetProc "Toplevel1" 1
    button $top.but63 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #fff -borderwidth 0 -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -image image28 -pady 0 -text Button 
    vTcl:DefineAlias "$top.but63" "stopButton" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab64 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -image image29 -text Label 
    vTcl:DefineAlias "$top.lab64" "vinylRecordImage" vTcl:WidgetProc "Toplevel1" 1
    vTcl::widgets::ttk::scrolledlistbox::CreateCmd $top.scr65 \
        -background $vTcl(actual_gui_bg) -height 75 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 125 
    vTcl:DefineAlias "$top.scr65" "playList" vTcl:WidgetProc "Toplevel1" 1

    $top.scr65.01 configure -background white \
        -cursor xterm \
        -disabledforeground #a3a3a3 \
        -font TkFixedFont \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor #d9d9d9 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10
    label $top.lab76 \
        -activebackground #f9f9f9 -activeforeground black -background #fff \
        -borderwidth 0 -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -image image26 -text Label 
    vTcl:DefineAlias "$top.lab76" "previousButton" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $top.tLa90 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -state disabled 
    vTcl:DefineAlias "$top.tLa90" "bottomBar" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.tLa90
    ttk::scale $top.tSc94 \
        -length 100 -takefocus {} 
    vTcl:DefineAlias "$top.tSc94" "TScale2" vTcl:WidgetProc "Toplevel1" 1
    button $top.but97 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #fff -borderwidth 0 -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -image image20 -pady 0 -text Button 
    vTcl:DefineAlias "$top.but97" "addSongsToPlayListButton" vTcl:WidgetProc "Toplevel1" 1
    button $top.but98 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #fff -borderwidth 0 -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -image image22 -pady 0 -text Button 
    vTcl:DefineAlias "$top.but98" "deleteSongsFromPlaylistButton" vTcl:WidgetProc "Toplevel1" 1
    button $top.but103 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -borderwidth 0 \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -image image21 -pady 0 -text Button 
    vTcl:DefineAlias "$top.but103" "Button9" vTcl:WidgetProc "Toplevel1" 1
    button $top.but105 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -borderwidth 0 \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -image image23 -pady 0 -text Button 
    vTcl:DefineAlias "$top.but105" "Button10" vTcl:WidgetProc "Toplevel1" 1
    button $top.but107 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -borderwidth 0 \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -image image27 -pady 0 -text Button 
    vTcl:DefineAlias "$top.but107" "Button11" vTcl:WidgetProc "Toplevel1" 1
    ttk::scale $top.tSc46 \
        -length 100 -takefocus {} 
    vTcl:DefineAlias "$top.tSc46" "TScale2_2" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab47 \
        -in $top -x 300 -y 20 -anchor nw -bordermode ignore 
    place $top.tPr48 \
        -in $top -x 270 -y 110 -width 340 -relwidth 0 -height 7 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tLa51 \
        -in $top -x 580 -y 90 -width 29 -height 19 -anchor nw \
        -bordermode ignore 
    place $top.tLa53 \
        -in $top -x 270 -y 90 -width 29 -height 19 -anchor nw \
        -bordermode ignore 
    place $top.but61 \
        -in $top -x 390 -y 140 -anchor nw -bordermode ignore 
    place $top.but62 \
        -in $top -x 440 -y 140 -anchor nw -bordermode ignore 
    place $top.but63 \
        -in $top -x 490 -y 140 -anchor nw -bordermode ignore 
    place $top.lab64 \
        -in $top -x 0 -y 0 -anchor nw -bordermode ignore 
    place $top.scr65 \
        -in $top -x 0 -y 200 -width 686 -relwidth 0 -height 280 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab76 \
        -in $top -x 340 -y 140 -anchor nw -bordermode ignore 
    place $top.tLa90 \
        -in $top -x 0 -y 480 -width 686 -relwidth 0 -height 49 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tSc94 \
        -in $top -x 0 -relx 0.029 -y 0 -rely 0.932 -width 0 -relwidth 0.147 \
        -height 26 -anchor nw -bordermode ignore 
    place $top.but97 \
        -in $top -x 660 -y 170 -width 17 -height 17 -anchor nw \
        -bordermode ignore 
    place $top.but98 \
        -in $top -x 630 -y 170 -width 18 -height 18 -anchor nw \
        -bordermode ignore 
    place $top.but103 \
        -in $top -x 640 -y 482 -width 42 -relwidth 0 -height 42 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but105 \
        -in $top -x 600 -y 482 -width 42 -relwidth 0 -height 42 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but107 \
        -in $top -x 570 -y 490 -width 26 -height 26 -anchor nw \
        -bordermode ignore 
    place $top.tSc46 \
        -in $top -x 0 -relx 0.247 -y 0 -rely 0.932 -width 0 -relwidth 0.147 \
        -height 0 -relheight 0.049 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

